#### general settings
name: Dual_Path_RNN
use_tb_logger: true
num_spks: 6
#### datasets
datasets:
  train:
    dataroot_mix: /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_mix.scp
    dataroot_targets: [/Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_1.scp, 
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_2.scp, /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_3.scp,
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_4.scp, /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_5.scp,
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/tr_6.scp]

  val:
    dataroot_mix: /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_mix.scp
    dataroot_targets: [/Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_1.scp,
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_2.scp, /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_3.scp,
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_4.scp, /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_5.scp,
    /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/cv_6.scp]
  
  dataloader_setting:
    shuffle: true
    num_workers: 1  # per GPU
    batch_size: 1
  
  audio_setting:
    sample_rate: 160000
    chunk_size: 256
    least_size: 128
    

#### network structures
Dual_Path_RNN:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  num_spks: 6

#### training settings: learning rate scheme, loss
train:
  epoch: 100
  early_stop: 10
  path: /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/checkpoint
  gpuid: [7]

#### Optimizer settings
optim:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 5e-4
  momentum: 0
  weight_decay: 0
  clip_norm: 5

#### scheduler settings
scheduler:
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5

#### Resume training settings
resume:
  state: false
  path: /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/checkpoint


#### logger
logger:
  name: DPCL
  path: /Users/elijahjohnson/Documents/GitHub/Dual-Path-RNN-Pytorch/checkpoint
  screen: true
  tofile: false
  print_freq: 1000